/**
 * Player cards as a build artifact.
 *
 * `src/data/cards.json` is generated by `scripts/build-cards.ts` (computeCards
 * against the pipeline output) and committed as static data — no sqlite, no
 * runtime database, no `process.cwd()` gotcha.
 */

import cardsJson from '@/data/cards.json';
import type { PlayerCardData } from './types';

/** card_balance D8: the card set version, stamped onto every card by build-cards.ts and
 *  read back by storage (`CURRENT_CARD_SET_VERSION` in `@/storage`) to flag a
 *  drafted/rostered card set older than the one currently shipped. Bump this whenever
 *  `computeCards`'s output changes (positions, rarity, badges, ratings). */
export const CARD_SET_VERSION = '2025-26.2';

let cache: PlayerCardData[] | null = null;

export function getAllCards(): PlayerCardData[] {
  // The JSON's structurally-inferred type doesn't exactly match PlayerCardData
  // (e.g. SeasonStat.fta isn't in the pipeline's SeasonStat table, and unused
  // columns like fg2a are) — go through `unknown` for the same "trust the
  // build artifact's shape" cast `getAllCards()` always did.
  if (!cache) cache = cardsJson as unknown as PlayerCardData[];
  return cache;
}

export function getCardById(id: string): PlayerCardData | undefined {
  return getAllCards().find(c => c.id === id);
}
