/**
 * Player cards as a build artifact.
 *
 * `src/data/cards.json` is generated by `scripts/build-cards.ts` (computeCards
 * against the pipeline output) and committed as static data — no sqlite, no
 * runtime database, no `process.cwd()` gotcha.
 */

import cardsJson from '@/data/cards.json';
import type { PlayerCardData } from './types';

let cache: PlayerCardData[] | null = null;

export function getAllCards(): PlayerCardData[] {
  // The JSON's structurally-inferred type doesn't exactly match PlayerCardData
  // (e.g. SeasonStat.fta isn't in the pipeline's SeasonStat table, and unused
  // columns like fg2a are) — go through `unknown` for the same "trust the
  // build artifact's shape" cast `getAllCards()` always did.
  if (!cache) cache = cardsJson as unknown as PlayerCardData[];
  return cache;
}

export function getCardById(id: string): PlayerCardData | undefined {
  return getAllCards().find(c => c.id === id);
}
