import path from 'path';
import { test, expect } from '@playwright/test';
import { dismissSplash, clickPastSplash } from './helpers/splash';

/**
 * Covers the game-results-visibility fix (SeasonView/GameView): a freshly-played game's
 * result must NOT reach the schedule/standings until the user watches it to completion
 * and hits "Continue to Schedule" — leaving early via "Exit Game" must discard it, not
 * silently save it. Uses a fixed-id fixture (`tests/fixtures/season-fixture.json`,
 * regenerated by `scripts/build-e2e-season-fixture.ts`) imported through the rosters
 * page's real Import flow, so this exercises the actual GameStore/import code path
 * rather than seeding storage directly.
 */

const FIXTURE_PATH = path.resolve(__dirname, 'fixtures', 'season-fixture.json');
const ROSTER_NAME = 'E2E Season Fixture';

test('leaving a fresh game early discards it; finishing and continuing saves it', async ({ page }) => {
  page.on('dialog', (dialog) => dialog.accept());

  // Start clean: delete any leftover roster (and its season) from a previous run. The
  // rosters list loads asynchronously (IndexedDB read + a cloud pull) after navigation,
  // so an immediate `.count()` here would race it and read "nothing to clean up" before
  // the stale row has actually rendered — wait for the loading state to clear first.
  await page.goto('/rosters');
  // The What's New splash mounts once per fresh context and swallows clicks (its
  // seen-state is IndexedDB, not in storageState) — clear it before touching anything.
  await dismissSplash(page);
  await expect(page.getByText('Loading Rosters...')).toHaveCount(0);
  const existingRow = page.locator('h2', { hasText: ROSTER_NAME }).first();
  if (await existingRow.count()) {
    const card = existingRow.locator('xpath=ancestor::div[contains(@class, "rounded-xl")][1]');
    await clickPastSplash(page, () => card.getByTitle('Delete Roster').click());
    await expect(existingRow).toHaveCount(0);
  }

  // Import the fixture (draft session + roster + fresh 7-game season, currentGame 0).
  await page.locator('input[type="file"]').setInputFiles(FIXTURE_PATH);
  await expect(page.getByText('Import complete')).toBeVisible();

  const rosterCard = page.locator('h2', { hasText: ROSTER_NAME }).first()
    .locator('xpath=ancestor::div[contains(@class, "rounded-xl")][1]');
  await clickPastSplash(page, () => rosterCard.getByRole('button', { name: 'Play Season' }).click());
  await expect(page).toHaveURL(/\/season\?/);

  // Game 1 is next up and unplayed. Each schedule row's "Game N • Home/Away" label is
  // unique per row — climb from that leaf text to the row's own bordered wrapper rather
  // than matching on any div containing the substring (every ancestor div would match).
  const scheduleEntry = (n: number) =>
    page.getByText(new RegExp(`^Game ${n} • `))
      .locator('xpath=ancestor::div[contains(@class, "rounded-lg") and contains(@class, "border")][1]');
  await expect(scheduleEntry(1).getByText('Play')).toBeVisible();

  // --- Play, then leave before it finishes: nothing should be saved. ---
  await scheduleEntry(1).click();
  await expect(page.getByRole('button', { name: 'Tip Off' })).toBeVisible();
  await page.getByRole('button', { name: 'Tip Off' }).click();

  const exitGameButton = page.getByRole('button', { name: 'Exit Game' });
  await expect(exitGameButton).toBeVisible();
  // The finished-state CTA must not be reachable yet — the game just started.
  await expect(page.getByRole('button', { name: 'Continue to Schedule' })).toHaveCount(0);

  await exitGameButton.click();
  await expect(page.getByText('Leave this game?')).toBeVisible();
  await page.getByRole('button', { name: 'Leave Anyway' }).click();

  // Back on the schedule: game 1 is still unplayed, exactly as before.
  await expect(scheduleEntry(1).getByText('Play')).toBeVisible();
  await expect(scheduleEntry(1).getByText(/^[WL]$/)).toHaveCount(0);

  // --- Play again, skip to the end, and continue: this time it must save. ---
  await scheduleEntry(1).click();
  await page.getByRole('button', { name: 'Tip Off' }).click();
  await page.getByRole('button', { name: 'End' }).click();

  const continueButton = page.getByRole('button', { name: 'Continue to Schedule' });
  await expect(continueButton).toBeVisible();
  await expect(page.getByRole('button', { name: 'Exit Game' })).toHaveCount(0);
  await continueButton.click();

  // Back on the schedule: game 1 now shows a result, and game 2 is next up.
  await expect(scheduleEntry(1).getByText(/^[WL]$/)).toBeVisible();
  await expect(scheduleEntry(2).getByText('Play')).toBeVisible();

  const standingsRow = page.locator('tr', { hasText: 'E2E Test' });
  await expect(standingsRow).toBeVisible();
  const record = await standingsRow.locator('td').allTextContents();
  // #, Team, W, L, +/- — one of W or L must be 1 after exactly one game.
  expect([record[2], record[3]]).toContain('1');
});
