/**
 * The ONLY place a headshot URL is built (plan mobile_load D3/D4).
 *
 * Components used to request `/headshots/<id>.png` directly: a 1040x760 PNG of up to
 * 280 KB, even for a 26 px avatar, and the card fronts sent the same file through
 * Vercel's image optimizer, which re-transformed all 481 of them every four hours.
 * `scripts/ensure-headshots.mjs` now pre-generates two WebP sets under `public/headshots/`
 * and every consumer picks the one that fits:
 *
 *   96   avatars: play-role rows, assign popovers, roster rows, drag ghosts (20-48 px)
 *   480  card fronts and previews (rendered up to ~140 CSS px at 3x DPR)
 *
 * The id is the PLAYER id (`card.player.id`), not the card id: a drafted copy of a card
 * can carry a suffixed card id, but there is one headshot per player. A player without a
 * real photo has a placeholder under the same name, so a URL from here never 404s.
 *
 * `?v=<card set version>`: these files are served with a one-year immutable cache, and a
 * pipeline refresh overwrites them IN PLACE (a rookie's placeholder becomes a real photo,
 * a new season brings new portraits). The version in the URL is what makes every browser
 * and the service worker fetch the new file; bump `CARD_SET_VERSION` with every refresh.
 */

// Relative, not '@/': next.config.ts imports this file (through lib/cacheHeaders.ts), and
// Next's config loader does not resolve the path alias in transitively required modules.
import { CARD_SET_VERSION } from '../engine/cardSetVersion';

export type HeadshotSize = 96 | 480;

/** Generated by `ensure-headshots.mjs`, in this order. Keep the script and this in step. */
export const HEADSHOT_SIZES: readonly HeadshotSize[] = [96, 480];

export function headshotThumb(playerId: string, size: HeadshotSize): string {
  return `/headshots/${size}/${playerId}.webp?v=${CARD_SET_VERSION}`;
}

/**
 * What `next.config.ts` may cache aggressively (D5) and what `public/sw.js` caches,
 * cache-first (D11); a unit test keeps the service worker's own copy of both lists
 * identical. Everything else — navigations, RSC payloads, `/api/*`, Supabase — must stay
 * network-only: the HTML is auth-gated by `proxy.ts`, and a cached copy would bypass it.
 *
 * IMMUTABLE (one year): the URL changes whenever the content does. Build output is
 * content-hashed, headshots carry `?v=`, and `/art/` holds re-encoded hero, pack and
 * card-back art where new art always gets a NEW file name.
 */
export const IMMUTABLE_ASSET_PREFIXES: readonly string[] = ['/_next/static/', '/headshots/96/', '/headshots/480/', '/art/'];

/** LONG-LIVED (30 days): stable names with no version in the URL, so a replaced team logo
 *  or app icon must still reach users within a month. */
export const LONG_LIVED_ASSET_PREFIXES: readonly string[] = ['/logos/', '/icons/'];
