/**
 * The source of `/sw.js` (plan mobile_load D11), generated by `app/sw.js/route.ts`.
 *
 * An ASSET cache and nothing else. It answers same-origin GETs for the path prefixes in
 * `lib/headshotThumb.ts` from the cache and leaves EVERYTHING else to the network,
 * untouched: navigations, RSC payloads, `/api/*`, Supabase, any non-GET. That restraint is
 * the design. The HTML is auth-gated by `proxy.ts`, so a cached page would bypass the
 * gate — which is why the earlier `mobile_pwa_shell` plan (offline pages) was dropped.
 * This gives an installed PWA instant static assets on relaunch; it does not make the
 * game playable offline.
 *
 * Two caches, because they age differently:
 *  - `mb-static-<buildId>`: `/_next/static/`. Content-hashed, so never stale, but every
 *    deploy orphans the previous build's chunks: the whole cache is dropped on activate.
 *  - `mb-assets-v1`: thumbnails, art, logos, icons. It SURVIVES deploys — purging it per
 *    build would make a phone re-download ~9 MB of unchanged headshots on every push.
 *    Freshness comes from the URL instead: headshots carry `?v=<card set version>` (older
 *    versions are pruned on activate), `/art/` gets a new file name for new art, and the
 *    unversioned logos and icons are served stale-while-revalidate.
 *
 * It is a plain-JS string, not a bundled module, so that what the unit test executes (in
 * a `vm` with fake `caches`/`fetch`) is byte for byte what the browser runs.
 *
 * Kill switch: build with `NEXT_PUBLIC_DISABLE_SW=1` and `/sw.js` becomes a worker that
 * deletes its caches and unregisters itself; `ServiceWorkerRegistrar` stops registering.
 */

export interface ServiceWorkerOptions {
  buildId: string;
  cardSetVersion: string;
  immutablePrefixes: readonly string[];
  longLivedPrefixes: readonly string[];
  disabled?: boolean;
}

export const STATIC_CACHE_PREFIX = 'mb-static-';
export const ASSET_CACHE = 'mb-assets-v1';

export function buildServiceWorkerSource(options: ServiceWorkerOptions): string {
  if (options.disabled) {
    return `// Hoops Draft service worker: DISABLED build. Removes itself and its caches.
self.addEventListener('install', () => self.skipWaiting());
self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    for (const name of await caches.keys()) if (name.startsWith('mb-')) await caches.delete(name);
    await self.registration.unregister();
  })());
});
`;
  }

  const config = {
    staticCache: STATIC_CACHE_PREFIX + options.buildId,
    staticCachePrefix: STATIC_CACHE_PREFIX,
    assetCache: ASSET_CACHE,
    cardSetVersion: options.cardSetVersion,
    buildOutputPrefix: '/_next/static/',
    immutable: options.immutablePrefixes,
    longLived: options.longLivedPrefixes,
  };

  return `// Hoops Draft service worker. Generated by src/lib/serviceWorker.ts; read the comment there.
const CONFIG = ${JSON.stringify(config, null, 2)};

self.addEventListener('install', () => {
  // Safe to take over at once: no HTML is ever cached and build output is content-hashed,
  // so an old page and a new worker can never disagree about what a URL means.
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    for (const name of await caches.keys()) {
      if (name.startsWith(CONFIG.staticCachePrefix) && name !== CONFIG.staticCache) await caches.delete(name);
    }
    // Headshots of a previous card set: the app no longer asks for those URLs.
    const assets = await caches.open(CONFIG.assetCache);
    for (const request of await assets.keys()) {
      const url = new URL(request.url);
      if (url.pathname.startsWith('/headshots/') && url.searchParams.get('v') !== CONFIG.cardSetVersion) {
        await assets.delete(request);
      }
    }
    await self.clients.claim();
  })());
});

/** 'static' | 'immutable' | 'revalidate' | null (null = not ours, the network handles it). */
function strategyFor(request) {
  if (request.method !== 'GET' || request.mode === 'navigate') return null;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return null;
  const path = url.pathname;
  if (path.startsWith(CONFIG.buildOutputPrefix)) return 'static';
  if (CONFIG.immutable.some((prefix) => prefix !== CONFIG.buildOutputPrefix && path.startsWith(prefix))) return 'immutable';
  if (CONFIG.longLived.some((prefix) => path.startsWith(prefix))) return 'revalidate';
  return null;
}

/** Only a complete, same-origin 200 is worth keeping: never an error page served under a
 *  chunk's URL during a deploy, never a partial (206) or an opaque response. */
function cacheable(response) {
  return response && response.status === 200 && response.type === 'basic';
}

async function fetchAndStore(cache, request) {
  const response = await fetch(request);
  if (cacheable(response)) await cache.put(request, response.clone());
  return response;
}

async function cacheFirst(cacheName, request) {
  const cache = await caches.open(cacheName);
  return (await cache.match(request)) || fetchAndStore(cache, request);
}

async function staleWhileRevalidate(cacheName, request, event) {
  const cache = await caches.open(cacheName);
  const cached = await cache.match(request);
  const refresh = fetchAndStore(cache, request);
  if (!cached) return refresh;
  event.waitUntil(refresh.catch(() => {})); // offline: the cached copy is the answer
  return cached;
}

self.addEventListener('fetch', (event) => {
  const strategy = strategyFor(event.request);
  if (strategy === 'static') event.respondWith(cacheFirst(CONFIG.staticCache, event.request));
  else if (strategy === 'immutable') event.respondWith(cacheFirst(CONFIG.assetCache, event.request));
  else if (strategy === 'revalidate') event.respondWith(staleWhileRevalidate(CONFIG.assetCache, event.request, event));
  // else: do nothing, which leaves the request to the browser exactly as if no worker existed.
});
`;
}
